### ISSUE TITLE
Milestone3 Feedback

### ISSUE THREAD

**Issue by Iadel95** [ubco-W2022T1-cosc301/project-group01#1]
# Group01 Feedback

Update on the process: we decided to give everybody feedback on their Milestone 3, and then give you all an opportunity to re-submit after applying the feedback. 

There are some items here that will be noted as "for Milestone 5" - for those items, we don't expect you to complete that until Milestone 5.
For **all** other feedback items, you should apply the feedback and resubmit on Gradescope (we will reopen the submission page later this week).

You should take about one week from when you receive your feedback to resubmit your milestone, though this is somewhat flexible. The absolute last day to re-submit Milestone 3 is Nov. 24 at 6 PM (no grace period).

### Major feedback

- (For Milestone 5) It feels like there should be a bit more analysis done to explore the dataset a bit more. I agree your dataset is quite clean and straightforward, but perhaps you could consider expanding your research question, or considering some sub-research question. If you need to bring in some additional data, you're more than welcome to do that.

### Minor feedback

- Not a good idea to `print` dataframes, instead, just write it as `df` and it will print nicely in a table form

- Make sure you run a spell check to catch spelling errors, for e.g, this one: https://github.com/jupyterlab-contrib/spellchecker 

- df.plot() is not a very useful plot, suggest splitting it by subject or multiple plots

- Would be good to add some titles to your plots

- Suggest making a compound plot (2x2 or 1x4) so your plots take up less space. Here's a link to the multi-plot grids: https://seaborn.pydata.org/tutorial/axis_grids.html

- Distribution plots looks good, but is lacking explanation and detail of what you found (this comes later in your summary). Suggest having a one or two line "caption" for each plot

- for load_and_process_before(), suggest renaming the `df` parameter to "filename" so it's clear that `df` is a filename rather than a dataframe 

- dataframe is loaded twice, to avoid this, just use `df1` instead of `df2`

### Points of Pride

- Very useful to have comments with some explanation about what you're doing and why - thanks!

- The heatmap looks very useful, good idea!

- Axis titles and labels were done very well.

- Good decision to use median instead of mean!

- The analysis that you did was pretty good and you used visualizations effectively to communicate your questions and your intent! Well done

### Major feedback

- (For Milestone 5) It feels like there should be a bit more analysis done to explore the dataset a bit more. I agree your dataset is quite clean and straightforward, but perhaps you could consider expanding your research question, or considering some sub-research question. If you need to bring in some additional data, you're more than welcome to do that.

- Figure 2, 3, 4 is over-plotted, suggest jittering the plots so it's more informative, or choosing a different plot type (violin plot?)

### Minor feedback

- Looks like you went out of your way to make your first plot bad (by making the face colour grey). I'd suggest splitting this up into four plots, one for each subject

- Suggest making a compound plot (2x2 or 1x4) so your plots take up less space. Here's a link to the multi-plot grids: https://seaborn.pydata.org/tutorial/axis_grids.html

### Points of Pride

- Good decision to use median instead of mean!

### Major feedback

- (For Milestone 5) It feels like there should be a bit more analysis done to explore the dataset a bit more. I agree your dataset is quite clean and straightforward, but perhaps you could consider expanding your research question, or considering some sub-research question. If you need to bring in some additional data, you're more than welcome to do that.

### Minor Feedback

- the Pair plot can probably be adjusted to show less data (fewer columns), not everything needs ot be shown here, and there are some duplicates. Redundancies in the pair plot, suggest only showing one half of the pair plot. Try it by setting `corner=True`: https://stackoverflow.com/questions/34087126/plot-lower-triangle-in-a-seaborn-pairgrid

### Points of Pride

- Plot choices was excellent, very informative, and appropriate

- Analysis was useful and well done

**Comment by noahstaz** [comment]
Feedback was assessed
